### ISSUE TITLE
two more talker bases (with code!)

### ISSUE THREAD

**Issue by marado** [talkersource/talkersource.github.io#5]
Gawnuts - https://github.com/ataliba/Gawnuts , currently based on Mamnuts, used to be based on Awnuts (hence the name);
Awnuts - https://sourceforge.net/projects/awnuts/ , is based on NUTS 2.3.0

**Comment by wrprice** [comment]
Thanks for the links.

Forked Gawnuts into the org, so it's captured.  Importing from SF will happen sometime later when I've got the time to process it.  PRs welcome for the info pages, otherwise those on best-effort basis, too.

**Comment by wrprice** [comment]
After review...

1. I'd appreciate more up-front, open disclosure. Awnuts / SAMNUTS are names for NUTS forks that you (marado) authored.
2. Despite the project page on SourceForge, "Awnuts" doesn't appear to have ever been released in a fully-realized state.
    - version is 0.1
    - TODO file suggests a "usable" state was not planned until version 0.3
    - SF project was uploaded in late August or early September, 2003 (per Archive.org)
    - SF project last meaningful update was 12 September 2003 (approximately 1 month later)
    - SF project effectively abandoned by 28 July 2005 when it redirects viewers to your _PyTalker_ project
3. A code diff between Awnuts and NUTS 2.3.0 doesn't show much meaningful difference beyond translations from English and/or feature removals (which could be due to diffing against the wrong NUTS version).

Admittedly, I haven't written any submission or review guidelines for this archive and that's on me. But I'd like to feature code bases that are _notable_ in some way.  Those listed on the original _Talker Family Tree_ (back when it was actively maintained on Usenet) were "well-known" enough to meet that goal.  Since the point where `alt.talkers` went defunct, as examples of newer code, I've included your _PyTalker_ and _TalkerNode_ efforts because they are notable due to their implementation languages while most others use C.

Most of the other NUTS-derived code bases were _distributed_ and used/run by people _other than the original author(s)_, as with your _Mamnuts_ code, but I'm not sure if that's the case with the two that are the subject of this issue.  As I'm sure you know, every talker customized the code to some degree for their own "theme" because editing the code was the only way one could do that; however, it is **not a goal** of this archive to capture every distinct customization or work-in-progress fork.

For these reasons, I think Awnuts (SAMNUTS) and Gawnuts fall into a "personal project" bucket and do not meet the bar for inclusion in the archive as distinct codebases.  I will take it as a follow-up action to define some submission guidelines for the archive so that the criteria will be better understood in the future.  I hope you can understand and accept this decision.
