### ISSUE TITLE
NUTS 4 inclusion

### ISSUE THREAD

**Issue by BlindHunter95** [talkersource/talkersource.github.io#7]
After discovering the wonderful world of talkers, something intrigued me. NUTS 4, the fabled update that was not part of the talker source website (as far as I could tell) was lost to time. 
Thanks to the wayback machine, I've recovered a version of nuts4, specifically version 1.4.1.
I certainly think this should be hosted as part of talkersource.com, and so I've pushed the code to my own github repo, which can be found [here.](https://github.com/BlindHunter95/nuts4)

**Comment by wrprice** [comment]
Hi, and thanks for feedback on the site!  NUTS 4 is already included, but as a branch of the NUTS repo:

- http://talkersource.com/codebases/nuts4.html
- https://github.com/talkersource/nuts/tags

However, your message has alerted me that Github has changed the behavior of certain URLs, so the "Download archived releases" links on the site seem to point to an empty page instead of the tags.  I'll try to get that fixed soon.

Please let me know if you find reliable sources (the Wayback Machine is an excellent tool!) of any others missing from the site, or mentioned but noted as missing source code -- [NUTS 1.x](https://talkersource.com/codebases/nuts1.html) for example.
